### ISSUE TITLE
`NoAccessLogSanic` doesn't disable access_log

### ISSUE THREAD

**Issue by abatilo** [terrycain/sanic-json-logging#59]
Using the code right from the `examples/simple.py`:
```python
import logging

import sanic.response
import sanic.request

from sanic_json_logging import setup_json_logging, NoAccessLogSanic


app = NoAccessLogSanic('app1')
setup_json_logging(app)

logger = logging.getLogger('root')


async def log():
    logger.info('some informational message')


@app.route("/endpoint1", methods=['GET'])
async def endpoint1(request: sanic.request.Request) -> sanic.response.BaseHTTPResponse:
    await log()
    return sanic.response.text('')

app.run()
```

I have the following project (using [poetry](https://github.com/sdispater/poetry)):
```toml
[tool.poetry]
name = "nal"
version = "0.1.0"
description = ""
authors = ["Aaron <AaronBatilo@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
sanic = "^19.6"
sanic_json_logging = "^1.3"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```

When I run the project, everything starts up just fine:
```zsh
⇒  poetry run python -m nal.main
[2019-07-09 08:01:30 -0600] [20986] [INFO] Goin' Fast @ http://127.0.0.1:8000
{"timestamp": "2019-07-09T14:01:30.924731Z", "level": "INFO", "message": "Goin' Fast @ http://127.0.0.1:8000", "type": "log", "logger": "sanic.root", "filename": "app.py", "lineno": 1383}
[2019-07-09 08:01:30 -0600] [20986] [INFO] Starting worker [20986]
{"timestamp": "2019-07-09T14:01:30.926515Z", "level": "INFO", "message": "Starting worker [20986]", "type": "log", "logger": "sanic.root", "filename": "server.py", "lineno": 802}
```

But when I send a request (using [httpie](https://github.com/jakubroztocil/httpie)):
```zsh
⇒  http :8000/endpoint1
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 0
Content-Type: text/plain; charset=utf-8
Keep-Alive: 5
```

I still get the access logs:
```json
{
  "timestamp": "2019-07-09T14:02:23.807338Z",
  "level": "INFO",
  "message": "some informational message",
  "type": "log",
  "logger": "root",
  "filename": "main.py",
  "lineno": 16,
  "req_id": "4efb221f-a142-4604-b593-d8e72a69faa6"
}
{
  "timestamp": "2019-07-09T14:02:23.807491Z",
  "level": "INFO",
  "method": "GET",
  "path": "/endpoint1",
  "remote": "127.0.0.1:51702",
  "user_agent": "HTTPie/1.0.2",
  "host": "localhost:8000",
  "response_time": 0,
  "req_id": "28f6ae3d-0e31-4573-819f-4cb852939ee8",
  "logger": "sanic.access",
  "status_code": 200,
  "length": 0,
  "type": "access"
}
```

I would expect that all the access logs are disabled since I'm using `NoAccessLogSanic` and all.
